### ISSUE TITLE
关于img的默认display样式的问题

### ISSUE THREAD

**Issue by duskcloudxu** [XJIANBIN/Front-end-Developer-Questions#1]
感谢一下你的整理，但是在学习的过程中发现了一点问题。
在行内元素与块状元素的问题中你提到了img是inline元素，但是我寻思我平时也没有每次要重新设置img的display属性啊……
后来试了下img的width属性是的确可以对产生影响的，但是它也的确不是block元素
查了下img的默认display属性是：inline-block，指它既有行内元素的特征（除了本身内容以外不会占有额外空间）也可以直接设定宽高
大概就是这样了（逃

**Comment by duskcloudxu** [comment]
update一下：我发现在HTML5之前的确所有元素要不就是inline要不就是block……所以应该是这个问题本身提的有些不好？

>  block and inline elements are no longer defined in HTML 5
from https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements

**Comment by XJIANBIN** [comment]
你好，我这边就在正文里面加上这个扩展阅读吧！挺好的，Keep fighting 。
